import pandas as pd
richest_nationality = pd.read_csv('advanced/pandas/top_100_richest.csv',usecols=['nationality']).squeeze()
print(f'Top 100 Richest People Nationality are\n{richest_nationality}')
print('==================================================================================')
print(f'Top 100 Richest People Nationality counts are\n{richest_nationality.value_counts()}')
print('==================================================================================')
print(f'Top 100 Richest People Nationality of 50th to 60th are \n{richest_nationality[50:60]}')
print('==================================================================================')
richest_info = pd.read_csv('advanced/pandas/top_100_richest.csv',usecols=['name','net_worth'], index_col='name')
print(f'Richest People in the world with their names and networth are \n{richest_info}')
print('==================================================================================')
richest = pd.read_csv('advanced/pandas/top_100_richest.csv',usecols=['name','age'], index_col='name').squeeze()
print(f'Richest People in the world with their names and age are \n{richest}')
oldest = richest.idxmax()
print(f'The oldest Rich person is {oldest}')
print(f'The oldest Rich person is {richest[oldest]}')
youngest = richest.idxmin()
print(f'The youngest Rich person is {youngest}')
print(f'The youngest Rich person is {richest[youngest]}')
print('The average age for the richest people is ',richest.mean().round()) 
richest.to_csv('advanced/pandas/sample.csv')
pd.read_csv('advanced/pandas/sample.csv')

